[build-system]
requires = [
    "wheel",    
    "setuptools",
    "setuptools_scm[toml]",
    "cmake_build_extension",
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3